-- ゲーム全体で共有する設定値。
local Config = {
    BOARD_SIZE = 5,
    CENTER = 3,
    CELL_SIZE = 32,
    DEFAULT_REFRESH_RATE = 30,
    CURSOR_KEY_REPEAT_INITIAL_DELAY_MS = 300,
    CURSOR_KEY_REPEAT_INTERVAL_MS = 80,
    NEXT_PREVIEW_COUNT = 3,
    MAX_UNDO_COUNT = 1,
    MAX_REWIND_USES = 3,
    REWIND_HOLD_DURATION_MS = 800,
    SCORE_MULTIPLIER = 100,
    COMBO_SCORE_COEFFICIENT = 2,
    COMBO_SCORE_EXPONENT = 1.5,
    PREVIEW_ROTATION_MAX_DEGREES = 200,
    PREVIEW_ROTATION_EVALUATION_MULTIPLIER = 0.1,
    PREVIEW_ROTATION_DEGREES_PER_POINT = 0.1,
    PREVIEW_IMPULSE_ROTATION_DEGREES = 5,
    PREVIEW_IMPULSE_DECAY = 0.7,
    DIRECTION = { DOWN = 1, LEFT = 2, RIGHT = 3, UP = 4 },
    GAME_STATE = {
        TITLE = "TITLE", PLAYING = "PLAYING", DROPPING = "DROPPING",
        MERGING = "MERGING", ROTATING = "ROTATING", UNDO_ROTATING = "UNDO_ROTATING",
        NEXT_ANIM = "NEXT_ANIM", HOLD_ANIM = "HOLD_ANIM", PAUSED = "PAUSED",
        GAME_OVER = "GAME_OVER",
    },
}

Config.NEXT_QUEUE_COUNT = Config.NEXT_PREVIEW_COUNT + 1
Config.BOARD_X = 100 + 32
Config.BOARD_Y = 48
Config.NEXT_BOX_X = 343 - 24
Config.NEXT_LABEL_X = Config.NEXT_BOX_X
Config.NEXT_BOX_Y = 48
Config.NEXT_BOX_WIDTH = 25
Config.NEXT_BOX_HEIGHT = 20
Config.NEXT_BOX_GAP = 4
Config.HOLD_BOX_X = 80
Config.HOLD_LABEL_X = 64
Config.HOLD_BOX_Y = 48
Config.PANEL_OFFSET_X = 0
Config.PANEL_OFFSET_Y = 128

GameConfig = Config
return Config
