-- ゲーム全体で共有する設定値。
local DEBUG_FLAG = true -- デバッグ用フラグ。trueの場合はデバッグ情報を表示する。

local Config = {
	-- システム.
    DEFAULT_REFRESH_RATE = 30, -- FPS.
    SHOW_AUTO_PLAY_MENU_ITEM = DEBUG_FLAG and true or false, -- OSメニューにAuto Playを表示する.
	SHOW_FPS = DEBUG_FLAG and true or false, 	-- FPS表示.
    SCREEN_WIDTH = 400,
    SCREEN_HEIGHT = 240,
    SCREEN_CENTER_X = 200, -- 画面の中心X座標.
	SCREEN_CENTER_Y = 120, -- 画面の中心Y座標.
    MENU_BACKGROUND_LOAD = "OFF", -- OFF/LOW/MEDIUM/HIGH.
    SHOW_MENU_BACKGROUND_MENU_ITEM = false, -- OSメニューに背景負荷切り替えを表示する.
	
	-- メインゲーム.
    BOARD_SIZE = 5, -- 盤面のサイズ.
    CENTER = 3, -- 盤面の中心.
    CELL_SIZE = 32, -- 盤面のセルのサイズ.
    CURSOR_KEY_REPEAT_INITIAL_DELAY_MS = 300,
    CURSOR_KEY_REPEAT_INTERVAL_MS = 80,
    NEXT_PREVIEW_COUNT = 6,
    MAX_UNDO_COUNT = 1, -- UNDOで戻せる手数の最大.
    MAX_REWIND_USES = 3, -- UNDOの使用回数の最大.
    REWIND_HOLD_DURATION_MS = 800,
    REWIND_GAUGE_WIDTH = 116,
    SCORE_MULTIPLIER = 100,
	-- NORMALモードのレベル関連.
    LEVEL_DROP_XP = 1,
    LEVEL_BASE_NEXT_XP = 20,
    LEVEL_NEXT_XP_INCREMENT = 5,
    LEVEL_UP_DISPLAY_FRAMES = 36, -- "LEVEL UP"表示のフレーム数.
    LEVEL_UP_BLINK_PERIOD_FRAMES = 10, -- 点滅を行うフレーム数.
    LEVEL_FIRST_TILE_XP = {
        [16] = 5,
        [32] = 10,
        [64] = 20,
        [128] = 35,
        [256] = 55,
        [512] = 80,
        [1024] = 110,
        [2048] = 150,
    },
	-- メニューの基準Y座標.
    TITLE_MENU_CENTER_Y = 132,
    TITLE_SUBMENU_CENTER_Y = 132,
    TITLE_PRACTICE_MENU_CENTER_Y = 108,
	-- PRACTICEモードの説明文の描画位置.
    TITLE_PRACTICE_DESCRIPTION_X = 12,
    TITLE_PRACTICE_DESCRIPTION_Y = 200,
    TITLE_PRACTICE_DESCRIPTION_WIDTH = 376,
    TITLE_PRACTICE_DESCRIPTION_HEIGHT = 18,
	-- コンボ関連.
    COMBO_SCORE_COEFFICIENT = 2,
    COMBO_SCORE_EXPONENT = 1.5,
    COMBO_BLINK_PERIOD_FRAMES = 3,
    COMBO_BLINK_ON_FRAMES = 1,
    COMBO_BLINK_DURATION_FRAMES = 20,
    COMBO_STEADY_DURATION_FRAMES = 30,
	-- TIME ATTACKモード.
    TIME_ATTACK_TARGET_VALUE = 64,
    TIME_ATTACK_256_TARGET_VALUE = 256,
    TIME_ATTACK_512_TARGET_VALUE = 512,
	-- CORE RUSHモード.
    CORE_RUSH_GAIN_DISPLAY_MS = 900,
    CORE_RUSH_COMPLETE_DISPLAY_MS = 2000, -- CORE RUSHモードのクリア表示時間.
    CORE_RUSH_VALUE_TILE_WIDTH = 36,
    CORE_RUSH_COMPLETE_CENTER_X = 200, -- CORE RUSHモードのクリア表示の中心座標X.
    CORE_RUSH_COMPLETE_CENTER_Y = 90, -- CORE RUSHモードのクリア表示の中心座標Y.
	-- PRACTICEモード.
    PRACTICE_TURN_WARNING_BLINK_PERIOD = 1200,
    PRACTICE_TURN_WARNING_BLINK_ON_DURATION = 600,
    PRACTICE_GOAL_X = 12, -- "GOAL"文字のX座標.
    PRACTICE_GOAL_Y = 80, -- "GOAL"文字のY座標.
	PRACTICE_OBJECTIVE_X = 12, -- 目的のX座標.
	PRACTICE_OBJECTIVE_Y = 100, -- 目的のY座標.
    PRACTICE_DESCRIPTION_X = 12,
    PRACTICE_DESCRIPTION_Y = 116,
    PRACTICE_DESCRIPTION_WIDTH = 112,
    PRACTICE_DESCRIPTION_HEIGHT = 12,
    PREVIEW_ROTATION_MAX_DEGREES = 200,
    PREVIEW_ROTATION_EVALUATION_MULTIPLIER = 0.1,
    PREVIEW_ROTATION_DEGREES_PER_POINT = 0.1,
    PREVIEW_IMPULSE_ROTATION_DEGREES = 5,
    PREVIEW_IMPULSE_DECAY = 0.7,
    ROTATION_EVALUATION_POSITION_RIGHT = 10,
    ROTATION_EVALUATION_POSITION_LEFT = -10,
    ROTATION_EVALUATION_POSITION_CENTER = 0,
    ROTATION_EVALUATION_DROP_POSITION_WEIGHT = 20,
    ROTATION_EVALUATION_DISAPPEARED_BLOCK_WEIGHT = -10,
    ROTATION_EVALUATION_MERGED_BLOCK_WEIGHT = 10,
    ROTATION_EVALUATION_MERGE_DIRECTION_LEFT = -5,
    ROTATION_EVALUATION_MERGE_DIRECTION_RIGHT = 5,
    ROTATION_EVALUATION_VERTICAL_DIRECTION_WEIGHT = 10,
	---@enum DIRECTION 方向.
    DIRECTION = { NONE = 0, DOWN = 1, LEFT = 2, RIGHT = 3, UP = 4 },
	---@enum LANGUAGE 言語.
    LANGUAGE = {
        JAPANESE = "ja",
        ENGLISH = "en",
    },
	---@enum SCENE シーンID.
    SCENE = {
        TITLE = "TITLE",
        GAME = "GAME",
        GAME_OVER = "GAME_OVER",
        ACHIEVEMENTS = "ACHIEVEMENTS",
        STATISTICS = "STATISTICS",
        SOUND_TEST = "SOUND_TEST",
    },
	---@enum GAME_MODE ゲームモード.
    GAME_MODE = {
        NORMAL = "NORMAL",
        TIME_ATTACK = "TIME_ATTACK",
        TIME_ATTACK_256 = "TIME_ATTACK_256",
        TIME_ATTACK_512 = "TIME_ATTACK_512",
        CORE_RUSH = "CORE_RUSH",
        PRACTICE = "PRACTICE",
    },
	---@enum GAME_PHASE ゲームの進行フェーズ.
    GAME_PHASE = {
        INPUT = "INPUT",
        DROPPING = "DROPPING",
        MERGING = "MERGING",
        ROTATING = "ROTATING",
        UNDO_ROTATING = "UNDO_ROTATING",
        NEXT_ANIM = "NEXT_ANIM",
        HOLD_ANIM = "HOLD_ANIM",
        PAUSED = "PAUSED",
    },
	---@enum GAME_RESULT ゲームの結果.
    GAME_RESULT = {
        GAME_OVER = "GAME_OVER",
        TIME_UP = "TIME_UP",
        VICTORY = "VICTORY",
    },
}

Config.NEXT_QUEUE_COUNT = Config.NEXT_PREVIEW_COUNT + 1
Config.BOARD_X = 100 + 32
Config.BOARD_Y = 54
Config.NEXT_BOX_X = 343 - 24
Config.NEXT_LABEL_X = Config.NEXT_BOX_X
Config.NEXT_BOX_Y = 48
Config.NEXT_BOX_WIDTH = 25
Config.NEXT_BOX_HEIGHT = 20
Config.NEXT_BOX_GAP = 4
Config.HOLD_BOX_X = 80
Config.HOLD_LABEL_X = 64
Config.HOLD_BOX_Y = 48
Config.PANEL_OFFSET_X = 0
Config.PANEL_OFFSET_Y = 128
Config.DANGER_ICON_SIZE = 20
Config.DANGER_ICON_OFFSET = 4
Config.DANGER_ICON_BLINK_PERIOD = 600
Config.DANGER_ICON_BLINK_ON_DURATION = 300
Config.ROTATION_DIRECTION_ARROW_OFFSET_Y = -Config.CELL_SIZE * 0.4
Config.ROTATION_DIRECTION_ARROW_MIN_LENGTH = 12
Config.ROTATION_DIRECTION_ARROW_MAX_LENGTH = 24
Config.ROTATION_DIRECTION_ARROW_HEAD_LENGTH = 6
Config.ROTATION_DIRECTION_ARROW_HEAD_WIDTH = 4
Config.ROTATION_DIRECTION_ARROW_MAX_EVALUATION =
    Config.PREVIEW_ROTATION_MAX_DEGREES * Config.PREVIEW_ROTATION_DEGREES_PER_POINT

GameConfig = Config
return Config
