-- ゲーム全体で共有する設定値。
local Config = {
	-- システム.
    DEFAULT_REFRESH_RATE = 30, -- FPS.
	-- メインゲーム.
    BOARD_SIZE = 5, -- 盤面のサイズ.
    CENTER = 3, -- 盤面の中心.
    CELL_SIZE = 32, -- 盤面のセルのサイズ.
    CURSOR_KEY_REPEAT_INITIAL_DELAY_MS = 300,
    CURSOR_KEY_REPEAT_INTERVAL_MS = 80,
    NEXT_PREVIEW_COUNT = 3,
    MAX_UNDO_COUNT = 1, -- UNDOで戻せる手数の最大.
    MAX_REWIND_USES = 3, -- UNDOの使用回数の最大.
    REWIND_HOLD_DURATION_MS = 800,
    REWIND_GAUGE_WIDTH = 116,
    SCORE_MULTIPLIER = 100,
    COMBO_SCORE_COEFFICIENT = 2,
    COMBO_SCORE_EXPONENT = 1.5,
    COMBO_BLINK_PERIOD_FRAMES = 3,
    COMBO_BLINK_ON_FRAMES = 1,
    COMBO_BLINK_DURATION_FRAMES = 20,
    COMBO_STEADY_DURATION_FRAMES = 30,
    TIME_ATTACK_LIMIT_MS = 60000,
    PREVIEW_ROTATION_MAX_DEGREES = 200,
    PREVIEW_ROTATION_EVALUATION_MULTIPLIER = 0.1,
    PREVIEW_ROTATION_DEGREES_PER_POINT = 0.1,
    PREVIEW_IMPULSE_ROTATION_DEGREES = 5,
    PREVIEW_IMPULSE_DECAY = 0.7,
    ROTATION_EVALUATION_POSITION_RIGHT = 10,
    ROTATION_EVALUATION_POSITION_LEFT = -10,
    ROTATION_EVALUATION_POSITION_CENTER = 0,
    ROTATION_EVALUATION_DROP_POSITION_WEIGHT = 20,
    ROTATION_EVALUATION_DISAPPEARED_BLOCK_WEIGHT = -10,
    ROTATION_EVALUATION_MERGED_BLOCK_WEIGHT = 10,
    ROTATION_EVALUATION_MERGE_DIRECTION_LEFT = -5,
    ROTATION_EVALUATION_MERGE_DIRECTION_RIGHT = 5,
    ROTATION_EVALUATION_VERTICAL_DIRECTION_WEIGHT = 10,
	-- 方向.
    DIRECTION = { DOWN = 1, LEFT = 2, RIGHT = 3, UP = 4 },
	-- シーンID.
    SCENE = {
        TITLE = "TITLE",
        GAME = "GAME",
        GAME_OVER = "GAME_OVER",
        ACHIEVEMENTS = "ACHIEVEMENTS",
        STATISTICS = "STATISTICS",
    },
    GAME_MODE = {
        NORMAL = "NORMAL",
        TIME_ATTACK = "TIME_ATTACK",
    },
    GAME_PHASE = {
        INPUT = "INPUT",
        DROPPING = "DROPPING",
        MERGING = "MERGING",
        ROTATING = "ROTATING",
        UNDO_ROTATING = "UNDO_ROTATING",
        NEXT_ANIM = "NEXT_ANIM",
        HOLD_ANIM = "HOLD_ANIM",
        PAUSED = "PAUSED",
    },
    GAME_RESULT = {
        GAME_OVER = "GAME_OVER",
        TIME_UP = "TIME_UP",
    },
}

Config.NEXT_QUEUE_COUNT = Config.NEXT_PREVIEW_COUNT + 1
Config.BOARD_X = 100 + 32
Config.BOARD_Y = 54
Config.NEXT_BOX_X = 343 - 24
Config.NEXT_LABEL_X = Config.NEXT_BOX_X
Config.NEXT_BOX_Y = 48
Config.NEXT_BOX_WIDTH = 25
Config.NEXT_BOX_HEIGHT = 20
Config.NEXT_BOX_GAP = 4
Config.HOLD_BOX_X = 80
Config.HOLD_LABEL_X = 64
Config.HOLD_BOX_Y = 48
Config.PANEL_OFFSET_X = 0
Config.PANEL_OFFSET_Y = 128
Config.DANGER_ICON_SIZE = 20
Config.DANGER_ICON_OFFSET = 4
Config.DANGER_ICON_BLINK_PERIOD = 600
Config.DANGER_ICON_BLINK_ON_DURATION = 300
Config.ROTATION_DIRECTION_ARROW_OFFSET_Y = -Config.CELL_SIZE * 0.4
Config.ROTATION_DIRECTION_ARROW_MIN_LENGTH = 12
Config.ROTATION_DIRECTION_ARROW_MAX_LENGTH = 24
Config.ROTATION_DIRECTION_ARROW_HEAD_LENGTH = 6
Config.ROTATION_DIRECTION_ARROW_HEAD_WIDTH = 4
Config.ROTATION_DIRECTION_ARROW_MAX_EVALUATION =
    Config.PREVIEW_ROTATION_MAX_DEGREES * Config.PREVIEW_ROTATION_DEGREES_PER_POINT

GameConfig = Config
return Config
